# Generated by Django 5.0 on 2024-03-28 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('genre', models.CharField(choices=[('SF', 'Science-Fiction'), ('NF', 'Non-Fiction'), ('TH', 'Thriller and Action'), ('HO', 'Horror'), ('RO', 'Romance'), ('CO', 'Comedy'), ('OT', 'Other'), ('FE', 'Featured')], max_length=2)),
                ('body', models.TextField()),
                ('summary', models.CharField(max_length=300)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('rating', models.PositiveIntegerField(blank=True, null=True)),
                ('affiliate_link', models.URLField(blank=True, help_text='Enter the URL of the affiliate link for this product', null=True, verbose_name='Affiliate Link')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('is_blogger', 'Can create, read, update, and their posts')],
            },
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='blog.post')),
            ],
        ),
    ]
